require([
    'controllers/mainCtrl',
    'controllers/authCtrl',
    'controllers/langCtrl',
    'controllers/pollCreateCtrl',
    'controllers/pollListCtrl',
    'controllers/pollDetailsCtrl',
    'controllers/userCreateCtrl',
    'controllers/userListCtrl'
]);
