require([
    'directives/lang',
    'directives/tableGrid',
    'directives/chairGraph',
    'directives/inputCodePassword',
    'directives/inputTextStack',
    'directives/signInForm',
    'directives/markdownEditor'
]);
