require([
    'factories/jwtProvider',
    'factories/ioProvider',
    'factories/authProvider',
    'factories/swalProvider',
    'factories/userProvider',
    'factories/pollProvider',
    'factories/hostProvider'
]);
